POST http://localhost:3000/users
Content-Type: application/json

{
    "name":"testuser",
    "password":"1234",
    "email":"testemail@test.com"
}

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username":"arjshriv",
    "password":"coupdeate"
}

###
GET http://localhost:3000/data/gethomelinks
Content-Type: :application/json

###
POST http://localhost:3000/data/getAllMatchingShows
Content-Type: application/json

{
    "searchtxt":"money"
}
###
GET http://localhost:3000/data/getAllTrendingMovies
Content-Type: application/json

###
POST http://localhost:3000/users/getUserAuthentication
Content-Type: application/json

{"authorization":"Bearer eyJhbGciOiJIUzI1NiInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdCIsImlhdCI6MTYwODcyODA4M30.ibYftnl2Weq7AuKB3ptP9Pu4k2Y_VNkbI8qA7YheO4k"}

